import { StudentData } from './types';

export const MOCK_STUDENTS: (StudentData & { grade: string })[] = [
  {
    student_id: "S001",
    name: "Alex Johnson",
    gender: 'M',
    school_type: 'Govt',
    prior_gpa: 3.8,
    attendance_pct: 95,
    quiz_avg: 88,
    assign_avg: 92,
    midterm: 90,
    study_hours_wk: 15,
    on_time_submit_pct: 100,
    lms_logins_wk: 12,
    forum_posts: 5,
    parent_edu: "Bachelors",
    commute_min: 15,
    grade: "A"
  },
  {
    student_id: "S002",
    name: "Maria Garcia",
    gender: 'F',
    school_type: 'Private',
    prior_gpa: 2.1,
    attendance_pct: 68,
    quiz_avg: 45,
    assign_avg: 55,
    midterm: 48,
    study_hours_wk: 3,
    on_time_submit_pct: 60,
    lms_logins_wk: 2,
    forum_posts: 0,
    parent_edu: "Secondary",
    commute_min: 45,
    grade: "F"
  },
  {
    student_id: "S003",
    name: "Sam Lee",
    gender: 'M',
    school_type: 'Private',
    prior_gpa: 3.2,
    attendance_pct: 82,
    quiz_avg: 72,
    assign_avg: 78,
    midterm: 75,
    study_hours_wk: 8,
    on_time_submit_pct: 90,
    lms_logins_wk: 6,
    forum_posts: 12,
    parent_edu: "Masters",
    commute_min: 20,
    grade: "B"
  },
  {
    student_id: "S004",
    name: "Jordan Smith",
    gender: 'F',
    school_type: 'Govt',
    prior_gpa: 2.8,
    attendance_pct: 74,
    quiz_avg: 58,
    assign_avg: 62,
    midterm: 55,
    study_hours_wk: 4,
    on_time_submit_pct: 75,
    lms_logins_wk: 4,
    forum_posts: 1,
    parent_edu: "High School",
    commute_min: 30,
    grade: "D"
  },
  {
    student_id: "S005",
    name: "Taylor Reed",
    gender: 'F',
    school_type: 'Private',
    prior_gpa: 3.5,
    attendance_pct: 88,
    quiz_avg: 82,
    assign_avg: 85,
    midterm: 80,
    study_hours_wk: 10,
    on_time_submit_pct: 95,
    lms_logins_wk: 8,
    forum_posts: 3,
    parent_edu: "Bachelors",
    commute_min: 10,
    grade: "B+"
  }
];
